### ISSUE TITLE
Gradle multi-project support

### ISSUE THREAD

**Issue by nickjn92** [pulumi/pulumi-java#576]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
A "mono-repo" approach is currently not supported (at least ootb) through grade as `pulumi` is invoking everything from the current folder instead of using Gradle with correct args such as the subproject name.

A simple setup containing two separate pulumi projects with different stacks. They are defined as two separate subprojects `:services:app-cluster` and `:services:mgmt-cluster`.

*root settings.gradle(.kts)*
```
rootProject.name = "iac"
include(
    "libs:modules",
    "services:app-cluster",
    "services:mgmt-cluster",
    "testing:commons",
)
```

*Simplified dir structure*
```
settings.gradle
build.gradle
services/
  -> app-cluster/
       * build.gradle
       * Pulumi.yaml
       * Pulumi.dev.yaml
       * Pulumi.staging.yaml
       * Pulumi.production.yaml
   -> mgmt-cluster/
       * build.gradle
       * Pulumi.yaml
       * Pulumi.production.yaml
```

You shouldn't need to have any `settings.gradle` inside of the subproject directories but trying to run pulumi inside one of the subprojects you get the following error message.
```
error: failed to load language plugin java: could not read plugin [/home/nickjn92/.pulumi/bin/pulumi-language-java] stdout: EOF
```

Also it might be classic pebcak but I'm currently getting errors trying to run this by adding `gradle.settings` to each subproject and running `pulumi up` from those directories
```
  pulumi:pulumi:Stack (iac-app-cluster-kotlin-dev):
    Exception in thread "main" java.lang.IllegalArgumentException: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
...
Caused by: java.lang.IllegalArgumentException: expected environment variable: 'PULUMI_MONITOR', got: ...

```

**Comment by pawelprazak** [comment]
Would invoking `pulumi` from subproject dir, instead of parent dir, be a viable workaround?

**Comment by nickjn92** [comment]
Invoking `pulumi` from subproject dir would have the following consequences:
* Need to place a dummy `settings.gradle` file inside of the subproject dir, not the end of the world but not great. Whats the reason that `pulumi
* Pulumi now doesn't use the gradle wrapper and instead uses the local gradle installation
* The way that pulumi now invokes Gradle causes the multi-project setup to stop working properly. E.g. when using a multi-project setup you can create your own "plugins" which is just a collection of  dependencies etc using the `buildSrc` root folder in the directory. This is included when you generate a multi-project gradle project using the `gradle init wrapper` task. As an example, this `buildSrc` creates a plugin which can be referenced within the subprojects `build.gradle` file as 
```gradle
plugins {
    id("se.nickjn92.iac.application")
}
```
But this now results in an error after invoking with `pulumi`:
```
Diagnostics:
  pulumi:pulumi:Stack (iac-kotlin-dev):
    FAILURE: Build failed with an exception.
    * Where:
    Build file '/home/nickjn92/Desktop/pulumi-java/services/app-cluster/build.gradle.kts' line: 1
    * What went wrong:
    Plugin [id: 'se.nickjn92.iac.application'] was not found in any of the following sources:

```

**Comment by t0yv0** [comment]
Finally was able to look into this - sorry for the large delay. There's a couple of things here. 

### Gradle detection

The easy part is improving Gradle project detection logic a bit. I have a tentative fix in #682 that seems to work with the example `services/{app-cluster, mgmt-cluster}` structure like this:

- `cd services/app-cluster && pulumi up` works by calling `gradle` inside `services/app-cluster` working directory
- `cd services/mgmt-cluster && pulumi up` works similarly
- if there is a top-level `./gradlew` that sits alongside `settings.gradle` it will call into that instead of the global

Does this sound right? I'm relatively new to Gradle. Or should Pulumi try to invoke `gradle` in the root folder with some argument indicating which subproject to run?

### Plugins

Do you have a small example involving plugins I could try to test on? How do I `create your own "plugins" `?

### Main Class

Currently Pulumi relies on being able to override the main class in the Gradle project.  This is an undocumented requirement  - something we definitely should document. Typically in your `build.gradle` there will be an override hook:

```
application {
    mainClass = project.hasProperty("mainClass")
            ? project.getProperty("mainClass")
            : 'appcluster.App'
}
```

Pulumi uses it to hook into a custom main and compute which Pulumi plugins are in use in your stack, and then auto-install these plugins. 

Does this fundamentally conflict with multi-project setup? I wonder what we could do here. We could potentially abandon the attempt to auto-install plugins if this main class override does not work.

### Playground

I've made a little repo to play with the fix:

https://github.com/t0yv0/pulumi-java-576/blob/main/repro.sh

**Comment by nickjn92** [comment]
**Gradle detection**

> Does this sound right? I'm relatively new to Gradle. Or should Pulumi try to invoke gradle in the root folder with some argument indicating which subproject to run?

Typically you would invoke gradle from the root project directory with the subproject name. In the above example you would normally invoke it like 
```bash
./gradlew :services:app-cluster:<gradle-task-name>
or
./gradlew services:app-cluster:<gradle-task-name>
```
Where `:services:app-cluster` is the subproject name which you define in the root `settings.gradle(.kts)`, e.g.:
```
rootProject.name = "iac"
include(
    "libs:modules",
    "services:app-cluster",
    "services:mgmt-cluster",
    "testing:commons",
)
``` 
**Plugins**
So when you're initializing a new gradle project you could do the following
```bash
$ gradle init wrapper
Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 2
Select implementation language:
  1: C++
  2: Groovy
  3: Java
  4: Kotlin
  5: Scala
  6: Swift
Enter selection (default: Java) [1..6] 4
Split functionality across multiple subprojects?:
  1: no - only one application project
  2: yes - application and library projects
Enter selection (default: no - only one application project) [1..2] 2

Select build script DSL:
  1: Groovy
  2: Kotlin
Enter selection (default: Kotlin) [1..2] 2
```
This will create a standard multi-project build with kotlin flavor (although kotlin, groovy or java doesn't matter).
This will generate a `buildSrc` directory inside of the root directory. This directory contains a number of custom plugins that you can apply to any subproject. 

So the current issue is that since pulumi isn't invoking Gradle through the root, It has no knowledge of these custom plugins. As long as we can get pulumi to invoke the root Gradle these plugins should work fine :)

**Main class**

With regards to the main class "Issue" it was just a misunderstanding that you have clarified. Each subproject could define
```
application {
    mainClass = project.hasProperty("mainClass")
            ? project.getProperty("mainClass")
            : 'appcluster.App'
}
```

**Comment by pawelprazak** [comment]
Thank you @t0yv0 for looking into this, and thank you @nickjn92 for taking the time to help us understand the requirements and the problem space.

I'll try to collect my thought on the topic in a coherent manner but forgive me if they are a bit chaotic.

Regarding undocumented behaviour and Main classes, there are two requirements, the language host must be able to invoke two main methods:
- first `com.pulumi.bootstrap.internal.Main` (hardcoded) in the context of a (sub)project dependencies to extract pulumi plugin metadata form gradle dependencies
- second the user's entrypoint with the Pulumi program

Those are **separate** mechanisms that happen to live in the same code. I'm not worried about this part, we should be ok IMO.

Regarding a workaround that could work with a subset of problem space, as you've pointed out Anton, we can look for parent `settings.gradle` and try to parse it and invoke `./gradlew :<subproject-name>:<gradle-task-name>`, but there are at least two shortcoming of this approach:
- it will be build tool specific (not universal) and will become problematic when gradle decides to change their semantics - if there is a breaking change there, we'd have to either support only never version (if possible) or multiple versions, because of that I'm worried about long term maintainability
- it will not take into account the correct order of the sub-projects if they depend on each other, we might try to hack it around using the order of the sub-projects in the `settings.gradle` but that's not ideal.

Another question is how many levels of subprojects we should look for?

Having said that, probably **some support is better then no support** IMO and this sounds like a useful workaround.

I'm mainly worried about gradual reimplementation of the build tool specific behaviours inside out language host. Also not sure how this would work for maven.

I've thought about this requirement a lot, and the only long term and JVM-esque solution I can think of is build tool plugins.
We (or anyone in the community) should be able to write a build tool plugin that uses the internal build tool APIs and Pulumi Automation API to provide a build tool centric experience, rather than a Pulumi CLI driven experience we have now.
Both are useful, but probably for power users that have complex build systems a plugin would be a more natural approach.
Also writing build tool plugins is a common thing in JVM world, e.g. there are very popular docker plugins for gradle, maven and sbt (and probably other less known build tools).

**I'm very curious what is the community feedback on this**, and what direction we should be taking for the future development.

**Comment by mklueh** [comment]
I'm running into this exact issue with 0.5.4. Not sure what I'm doing wrong.

I've just dropped this example into my project (JDK 17 and Gradle 7.4.2) into a submodule and pressed the run icon.

https://www.pulumi.com/docs/get-started/kubernetes/review-project/

```
See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
13 actionable tasks: 2 executed, 11 up-to-date
Exception in thread "main" java.lang.IllegalArgumentException: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
	at com.pulumi.deployment.internal.DeploymentImpl$DeploymentState.lambda$fromEnvironment$2(DeploymentImpl.java:1660)
	at com.pulumi.core.Left.orThrow(Left.java:57)
	at com.pulumi.deployment.internal.DeploymentImpl$DeploymentState.fromEnvironment(DeploymentImpl.java:1666)
	at com.pulumi.deployment.internal.DeploymentImpl.fromEnvironment(DeploymentImpl.java:155)
	at com.pulumi.internal.PulumiInternal.fromEnvironment(PulumiInternal.java:41)
	at com.pulumi.Pulumi.withOptions(Pulumi.java:51)
	at com.pulumi.Pulumi.run(Pulumi.java:29)
	at com.myproject.infrastructure.kubernetes.DeploymentFactory.deploy(DeploymentFactory.java:28)
	at com.myproject.infrastructure.kubernetes.DeploymentFactory.main(DeploymentFactory.java:24)
Caused by: java.lang.IllegalArgumentException: expected environment variable: 'PULUMI_ENGINE', got: [USERDOMAIN_ROAMINGPROFILE, PROCESSOR_LEVEL, SESSIONNAME, ALLUSERSPROFILE, PROCESSOR_ARCHITECTURE, ANDROID_HOME, PSModulePath, SystemDrive, USERNAME, ProgramFiles(x86), TOOLBOX_VERSION, PATHEXT, DriverData, OneDriveConsumer, ProgramData, ProgramW6432, HOMEPATH, PROCESSOR_IDENTIFIER, POWERSHELL_DISTRIBUTION_CHANNEL, ProgramFiles, PUBLIC, windir, ZES_ENABLE_SYSMAN, LOCALAPPDATA, ChocolateyLastPathUpdate, PULUMI_MONITOR, USERDOMAIN, LOGONSERVER, JAVA_HOME, OneDrive, APPDATA, ChocolateyInstall, ChocolateyToolsLocation, CommonProgramFiles, Path, OS, COMPUTERNAME, PROCESSOR_REVISION, CLASSPATH, CommonProgramW6432, ComSpec, RUBYOPT, SystemRoot, TEMP, HOMEDRIVE, USERPROFILE, TMP, CommonProgramFiles(x86), NUMBER_OF_PROCESSORS, IDEA_INITIAL_DIRECTORY]
	at com.pulumi.core.internal.Environment.getEnvironmentVariable(Environment.java:42)
	... 7 more

FAILURE: Build failed with an exception.

```

**Comment by t0yv0** [comment]
@mklueh these programs are not supposed to be run via "run icon" but instead you're expected to run `pulumi up` on a command line - in fact the get started guide you linked has a next step suggestion of https://www.pulumi.com/docs/get-started/kubernetes/deploy-stack/ could you try that and see if that works?

**Comment by mklueh** [comment]
> @mklueh these programs are not supposed to be run via "run icon" but instead you're expected to run `pulumi up` on a command line - in fact the get started guide you linked has a next step suggestion of https://www.pulumi.com/docs/get-started/kubernetes/deploy-stack/ could you try that and see if that works?

Thanks, I'll try that. However I thought I could develop an actual application around it to spawn and manage cloud resources. Why can't it be executed from code directly and will this be possible in future?

**Comment by t0yv0** [comment]
The workflow you're asking for is possible with https://www.pulumi.com/docs/guides/automation-api/ however as of this moment it's not yet available for Java programs. I believe it will be available in the future for Java also.

**Comment by mklueh** [comment]
> The workflow you're asking for is possible with https://www.pulumi.com/docs/guides/automation-api/ however as of this moment it's not yet available for Java programs. I believe it will be available in the future for Java also.

Thanks, good to know!
