### ISSUE TITLE
pulumi java-gradle fails with cryptic message

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-java#817]
### What happened?

when build.gradle main class script changed from 

```
 mainClass = project.hasProperty("mainClass")
            ? project.getProperty("mainClass")
            : 'com.tejasoft.devops.iac.pulumi.gradle.GradlePulumiApp'
```

to 
` mainClass =  'com.tejasoft.devops.iac.pulumi.gradle.GradlePulumiApp'`

then `pulumi about`

fails with exception

```
G:\DWork\osource\cloudc\devops\pulumi\java\java-gradle>pulumi about
Exception in thread "main" java.lang.IllegalArgumentException: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

        at com.pulumi.deployment.internal.DeploymentImpl$DeploymentState.lambda$fromEnvironment$2(DeploymentImpl.java:1627)

        at com.pulumi.core.Left.orThrow(Left.java:57)

        at com.pulumi.deployment.internal.DeploymentImpl$DeploymentState.fromEnvironment(DeploymentImpl.java:1632)

        at com.pulumi.deployment.internal.DeploymentImpl.fromEnvironment(DeploymentImpl.java:158)

        at com.pulumi.internal.PulumiInternal.fromEnvironment(PulumiInternal.java:39)

        at com.pulumi.Pulumi.runAsync(Pulumi.java:39)

        at com.pulumi.Pulumi.run(Pulumi.java:28)

        at com.tejasoft.devops.iac.pulumi.gradle.GradlePulumiApp.main(GradlePulumiApp.java:10)

Caused by: java.lang.IllegalArgumentException: expected environment variable: 'PULUMI_MONITOR', got: [DCA_BU_ROOT..]

        at com.pulumi.core.internal.Environment.getEnvironmentVariable(Environment.java:42)

        ... 6 more

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:run'.

> Process 'command 'D:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe'' finished with non-zero exit value 1

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME  VERSION
java  unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in java: executable='d:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe' version='java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)' java='d:\Apps\Dev\langs\java\jdk\17.x\bin\java.exe' javac='17.0.2'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/nagkumar
User           nagkumar
Organizations  nagkumar, tejasoft

No dependencies found

```
Pulumi locates its logs in C:\Users\RAJANA~1\AppData\Local\Temp by default
warning: Failed to get information about the current stack: No current stack

### Steps to reproduce

change build main class as said above

### Expected Behavior

it should at least give proper error.. that is more easy to understand

### Actual Behavior

exception..

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nagkumar** [comment]
The same error is shown for `pulumi up` command too.

**Comment by pawelprazak** [comment]
This is expected behaviour, although not ideal user experience I admit.

This bit is required for plugin classpath auto discovery feature to work:
```
mainClass = project.hasProperty("mainClass")
            ? project.getProperty("mainClass")
            ...
```

I agree, the error handling should be corrected. Thank you for your report.

**Comment by pawelprazak** [comment]
Can reproduce in maven as well, by renaming `mainClass`->`mainClassS`:
```
<mainClassS>${project.groupId}.${project.artifactId}.App</mainClassS>
```

```
Pawes-MacBook-Pro:random pprazak$ pulumi about
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< com.pulumi.example:random >----------------------
[INFO] Building random 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ random ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/pprazak/repos/pulumi-java/tests/examples/random/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ random ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ random ---
[WARNING]
java.lang.IllegalArgumentException: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    at com.pulumi.deployment.internal.DeploymentImpl$DeploymentState.lambda$fromEnvironment$2 (DeploymentImpl.java:1627)
    at com.pulumi.core.Left.orThrow (Left.java:57)
    at com.pulumi.deployment.internal.DeploymentImpl$DeploymentState.fromEnvironment (DeploymentImpl.java:1632)
    at com.pulumi.deployment.internal.DeploymentImpl.fromEnvironment (DeploymentImpl.java:158)
    at com.pulumi.internal.PulumiInternal.fromEnvironment (PulumiInternal.java:39)
    at com.pulumi.Pulumi.runAsync (Pulumi.java:39)
    at com.pulumi.Pulumi.run (Pulumi.java:28)
    at com.pulumi.example.random.App.main (App.java:23)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.IllegalArgumentException: expected environment variable: 'PULUMI_MONITOR', got: [PATH, LC_TERMINAL, JAVA_HOME, TERM, COMMAND_MODE, CLOUDSDK_PYTHON, ITERM_SESSION_ID, COLORTERM, LOGNAME, XPC_SERVICE_NAME, PWD, TERM_PROGRAM_VERSION, MAVEN_CMD_LINE_ARGS, __CFBundleIdentifier, LC_TERMINAL_VERSION, SHELL, TERM_PROGRAM, LSCOLORS, SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS, MAVEN_PROJECTBASEDIR, SECURITYSESSIONID, OLDPWD, USER, CLICOLOR, ITERM_PROFILE, LaunchInstanceID, TMPDIR, SSH_AUTH_SOCK, XPC_FLAGS, TERM_SESSION_ID, __CF_USER_TEXT_ENCODING, LC_CTYPE, JENV_SHELL, COLORFGBG, HOME, SHLVL, JENV_LOADED]
    at com.pulumi.core.internal.Environment.getEnvironmentVariable (Environment.java:42)
    at com.pulumi.deployment.internal.DeploymentImpl$DeploymentState.fromEnvironment (DeploymentImpl.java:1632)
    at com.pulumi.deployment.internal.DeploymentImpl.fromEnvironment (DeploymentImpl.java:158)
    at com.pulumi.internal.PulumiInternal.fromEnvironment (PulumiInternal.java:39)
    at com.pulumi.Pulumi.runAsync (Pulumi.java:39)
    at com.pulumi.Pulumi.run (Pulumi.java:28)
    at com.pulumi.example.random.App.main (App.java:23)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:833)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.050 s
[INFO] Finished at: 2022-08-25T11:38:17+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project random: An exception occured while executing the Java class. Program run without the Pulumi engine available; re-run using the `pulumi` CLI: expected environment variable: 'PULUMI_MONITOR', got: [PATH, LC_TERMINAL, JAVA_HOME, TERM, COMMAND_MODE, CLOUDSDK_PYTHON, ITERM_SESSION_ID, COLORTERM, LOGNAME, XPC_SERVICE_NAME, PWD, TERM_PROGRAM_VERSION, MAVEN_CMD_LINE_ARGS, __CFBundleIdentifier, LC_TERMINAL_VERSION, SHELL, TERM_PROGRAM, LSCOLORS, SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS, MAVEN_PROJECTBASEDIR, SECURITYSESSIONID, OLDPWD, USER, CLICOLOR, ITERM_PROFILE, LaunchInstanceID, TMPDIR, SSH_AUTH_SOCK, XPC_FLAGS, TERM_SESSION_ID, __CF_USER_TEXT_ENCODING, LC_CTYPE, JENV_SHELL, COLORFGBG, HOME, SHLVL, JENV_LOADED] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME  VERSION
java  unknown

Host
OS       darwin
Version  12.4
Arch     x86_64

This project is written in java: executable='/Users/pprazak/.jenv/shims/java' version='openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)' javac='11.0.11' maven='Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)' gradle='7.5.1' java='/Users/pprazak/.jenv/shims/java'

Backend
Name           Pawes-MacBook-Pro.local
URL            file://~
User           pprazak
Organizations

No dependencies found

Pulumi locates its logs in /var/folders/nr/rqhf2hvn3wn8q_mjysz2gq6m0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

**Comment by pawelprazak** [comment]
I've made a small change that will make `pulumi about` no longer report build/compilation errors:
```
Pawes-MacBook-Pro:random pprazak$ pulumi about
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME  VERSION
java  unknown

Host
OS       darwin
Version  12.4
Arch     x86_64

This project is written in java: executable='/Users/pprazak/.jenv/shims/java' version='openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)' javac='11.0.11' maven='Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)' gradle='7.5.1' java='/Users/pprazak/.jenv/shims/java'

Backend
Name           Pawes-MacBook-Pro.local
URL            file://~
User           pprazak
Organizations

No dependencies found

Pulumi locates its logs in /var/folders/nr/rqhf2hvn3wn8q_mjysz2gq6m0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

This partially address the issue.

**Comment by pawelprazak** [comment]
An ideal solution would be to make the plugin discovery mechanism plumbing not visible to the user.

The challenge would be to find a way to accomplish this goal per each build provider, not only `gradle`.

In terms of gradle, init scripts looks promising as an option to not pollute user's build files.

**Comment by mklueh** [comment]
I'm facing the same problem, but only if I try to run it via gradle. If I instead use "pulumi up" it works
